// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserAddressStmt, err = db.PrepareContext(ctx, createUserAddress); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserAddress: %w", err)
	}
	if q.createUserPhoneStmt, err = db.PrepareContext(ctx, createUserPhone); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserPhone: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIdStmt, err = db.PrepareContext(ctx, getUserById); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserById: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserAddressStmt, err = db.PrepareContext(ctx, updateUserAddress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserAddress: %w", err)
	}
	if q.updateUserPhoneStmt, err = db.PrepareContext(ctx, updateUserPhone); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPhone: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserAddressStmt != nil {
		if cerr := q.createUserAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserAddressStmt: %w", cerr)
		}
	}
	if q.createUserPhoneStmt != nil {
		if cerr := q.createUserPhoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserPhoneStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIdStmt != nil {
		if cerr := q.getUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIdStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserAddressStmt != nil {
		if cerr := q.updateUserAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserAddressStmt: %w", cerr)
		}
	}
	if q.updateUserPhoneStmt != nil {
		if cerr := q.updateUserPhoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPhoneStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	createUserStmt        *sql.Stmt
	createUserAddressStmt *sql.Stmt
	createUserPhoneStmt   *sql.Stmt
	getUserByEmailStmt    *sql.Stmt
	getUserByIdStmt       *sql.Stmt
	getUserByUsernameStmt *sql.Stmt
	updateUserStmt        *sql.Stmt
	updateUserAddressStmt *sql.Stmt
	updateUserPhoneStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		createUserStmt:        q.createUserStmt,
		createUserAddressStmt: q.createUserAddressStmt,
		createUserPhoneStmt:   q.createUserPhoneStmt,
		getUserByEmailStmt:    q.getUserByEmailStmt,
		getUserByIdStmt:       q.getUserByIdStmt,
		getUserByUsernameStmt: q.getUserByUsernameStmt,
		updateUserStmt:        q.updateUserStmt,
		updateUserAddressStmt: q.updateUserAddressStmt,
		updateUserPhoneStmt:   q.updateUserPhoneStmt,
	}
}
